automista/automista/urls.py
from django.urls import path, include
from cars import views

app_name = 'cars'

urlpatterns = [
    path('cars/', include('cars.urls')),
    path('cars/', include('cars.urls', namespace='cars')),
    path('', views.car_list, name='car_list'),
    path('car/<int:car_id>/', views.car_detail, name='car_detail'),

]



automista/cars/urls.py
from django.urls import path
from . import views

app_name = 'cars'

urlpatterns = [
    path('', views.car_list, name='car_list'),
    path('car/<int:car_id>/', views.car_detail, name='car_detail'),
    path('my_view/', views.my_view, name='my_view'),
    path('bmw/', views.bmw_page, name='bmw_page'),
    path('mers/', views.mers_page, name='mers_page'),
    path('volks/', views.volks_page, name='volks_page'),
    path('ren/', views.ren_page, name='ren_page'),
    path('ford/', views.ford_page, name='ford_page'),
    path('audi/', views.audi_page, name='audi_page'),
    path('sko/', views.sko_page, name='sko_page'),
    path('niss/', views.niss_page, name='niss_page'),
    path('toyo/', views.toyo_page, name='toyo_page'),
    path('hyu/', views.hyu_page, name='hyu_page'),
    path('hon/', views.hon_page, name='hon_page'),
    path('chev/', views.chev_page, name='chev_page'),
    path('maz/', views.maz_page, name='maz_page'),
    path('cit/', views.cit_page, name='cit_page'),
    path('vol/', views.vol_page, name='vol_page'),
    path('fiat/', views.fiat_page, name='fiat_page'),
    path('lex/', views.lex_page, name='lex_page'),
    path('jeep/', views.jeep_page, name='jeep_page'),
    path('lr/', views.lr_page, name='lr_page'),
    path('che/', views.che_page, name='che_page'),
    path('dac/', views.dac_page, name='dac_page'),
    path('AfterButton/', views.AfterButton_page, name='AfterButton_page'),
    path('Obrob/', views.Obrob_page, name='Obrob_page'),
]

automista/automista/models/my_model.py
from django.db import models

class MyModel(models.Model):
    field1 = models.CharField(max_length=100)
    field2 = models.IntegerField()


automista/cars/models.py
from django.db import models

class Car(models.Model):
    make = models.CharField(max_length=100)
    model = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField()

    def __str__(self):
        return f"{self.make} {self.model}"


automista/cars/views.py
from django.shortcuts import render
from .models import Car

def bmw_page(request):
    return render(request, 'BMW.html')

def mers_page(request):
    return render(request, 'Mercedes-Benz.html')

def volks_page(request):
    return render(request, 'Volkswagen.html')

def ford_page(request):
    return render(request, 'Ford.html')

def audi_page(request):
    return render(request, 'audi.html')

def sko_page(request):
    return render(request, 'Skoda.html')

def niss_page(request):
    return render(request, 'Nissan.html')

def toyo_page(request):
    return render(request, 'Toyota.html')

def hyu_page(request):
    return render(request, 'Hyundai.html')

def hon_page(request):
    return render(request, 'Honda.html')

def chev_page(request):
    return render(request, 'Chevrolet.html')

def maz_page(request):
    return render(request, 'Mazda.html')

def cit_page(request):
    return render(request, 'Citroen.html')

def vol_page(request):
    return render(request, 'Volvo.html')

def fiat_page(request):
    return render(request, 'Fiat.html')

def lex_page(request):
    return render(request, 'Lexus.html')
def ren_page(request):
    return render(request, 'Renault.html')

def jeep_page(request):
    return render(request, 'Jeep.html')


def lr_page(request):
    return render(request, 'Land Rover.html')

def che_page(request):
    return render(request, 'Chery.html')

def dac_page(request):
    return render(request, 'Dacia.html')
def my_view(request):
    cars = Car.objects.all()
    context = {'cars': cars}
    return render(request, 'my_template.html', context)

def car_list(request):
    cars = Car.objects.all()
    return render(request, 'cars/car_list.html', {'cars': cars})

def car_detail(request, car_id):
    car = Car.objects.get(pk=car_id)
    return render(request, 'cars/car_detail.html', {'car': car})

def AfterButton_page(request):
    return render(request, 'AfterButtonCar.html')

def Obrob_page(request):
    return render(request, 'ObrabotkaDannih.html')

automista/cars/templates/BMW.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>BMW</title>
</head>
<body>
<header>
    <h1 style="margin-left: 500px;">Это все автомобили марки BMW что мы сейчас можем предложить вам:</h1>
</header>
<div style="display: flex; flex-wrap: wrap; justify-content: center;">
    <div class="card" style="width: 30rem; margin: 10px; border: 1px solid #000; text-align: center;">
        <img src="https://o.aolcdn.com/images/dims3/GLOB/crop/1920x1081+0+158/resize/800x450!/format/jpg/quality/85/http://o.aolcdn.com/hss/storage/midas/51b492c5e9b3ebcf3b33867a208a7fe6/203172643/01-2016-bmw-x5-xdrive40e-review.jpg" class="card-img-top" alt="BMWX5_2016" style="width: 480px; height: 250px; background-color: #f0f0f0; display: block; margin: 0 auto;">
        <div class="card-body">
            <hr style="position: middle;
  width: 100%;
  height: 2px;
  background-color: #000;
  border: none;
  transform: translateY(-50%);">
            <h5 class="card-title">BMW X5 2016</h5>
            <hr style="position: middle;
  width: 100%;
  height: 2px;
  background-color: #000;
  border: none;
  transform: translateY(-50%);">
            <p class="card-text">Двигатель - 3 л • Дизель
            </p>
            <hr style="position: middle;
  width: 100%;
  height: 2px;
  background-color: #000;
  border: none;
  transform: translateY(-50%);">
            <p class="card-text">Кол-во владельцев - 4
            </p>
            <hr style="position: middle;
  width: 100%;
  height: 2px;
  background-color: #000;
  border: none;
  transform: translateY(-50%);">
            <p class="card-text">В розыске - Да
            </p>
            <hr style="position: middle;
  width: 100%;
  height: 2px;
  background-color: #000;
  border: none;
  transform: translateY(-50%);">
            <a  href="{% url 'cars:AfterButton_page' %}" style="text-decoration: none; background-color: grey; color: yellow" onmouseover="this.style.color='yellow'; this.style.backgroundColor='blue';" onmouseout="this.style.color='black'; this.style.backgroundColor='transparent';">Договорится о встрече</a>
        </div>
    </div>

    <div class="card" style="width: 30rem; margin: 10px; border: 1px solid #000; text-align: center;">
        <img src="https://www.cnet.com/a/img/resize/911b086cb385d330c1be2cfb1f9ec4f115d88baa/hub/2018/09/13/4af817af-9e96-4d5f-8ba4-8d279e06b018/bmw-m5-2018-promo.jpg?auto=webp&fit=crop&height=675&width=1200" class="card-img-top" alt="BMWM52018" style="width: 480px; height: 250px; background-color: #f0f0f0; display: block; margin: 0 auto;">
        <div class="card-body">
            <hr style="position: middle;
  width: 100%;
  height: 2px;
  background-color: #000;
  border: none;
  transform: translateY(-50%);">
            <h5 class="card-title">BMW M5 2018</h5>
            <hr style="position: middle;
  width: 100%;
  height: 2px;
  background-color: #000;
  border: none;
  transform: translateY(-50%);">
            <p class="card-text">Двигатель - 4.39 л • Бензин
            </p>
            <hr style="position: middle;
  width: 100%;
  height: 2px;
  background-color: #000;
  border: none;
  transform: translateY(-50%);">
            <p class="card-text">Кол-во владельцев - 5
            </p>
            <hr style="position: middle;
  width: 100%;
  height: 2px;
  background-color: #000;
  border: none;
  transform: translateY(-50%);">
            <p class="card-text">В розыске - Нет
            </p>
            <hr style="position: middle;
  width: 100%;
  height: 2px;
  background-color: #000;
  border: none;
  transform: translateY(-50%);">
            <a  href="{% url 'cars:AfterButton_page' %}" style="text-decoration: none; background-color: grey; color: yellow" onmouseover="this.style.color='yellow'; this.style.backgroundColor='blue';" onmouseout="this.style.color='black'; this.style.backgroundColor='transparent';">Договорится о встрече</a>
        </div>
    </div>

    <div class="card" style="width: 30rem; margin: 10px; border: 1px solid #000; text-align: center;">
        <img src="https://cars.ua/thumb/car/20220517/w933/h622/q80/kupit-bmw-x7-xdrive-40d-m-sport-kiev-3141720.jpg" class="card-img-top" alt="BMWX72021" style="width: 480px; height: 250px; background-color: #f0f0f0; display: block; margin: 0 auto;">
        <div class="card-body">
            <hr style="position: middle;
  width: 100%;
  height: 2px;
  background-color: #000;
  border: none;
  transform: translateY(-50%);">
            <h5 class="card-title">BMW X7 2021</h5>
            <hr style="position: middle;
  width: 100%;
  height: 2px;
  background-color: #000;
  border: none;
  transform: translateY(-50%);">
            <p class="card-text">Двигатель - 4.39 л • Бензин
            </p>
            <hr style="position: middle;
  width: 100%;
  height: 2px;
  background-color: #000;
  border: none;
  transform: translateY(-50%);">
            <p class="card-text">Кол-во владельцев - 5
            </p>
            <hr style="position: middle;
  width: 100%;
  height: 2px;
  background-color: #000;
  border: none;
  transform: translateY(-50%);">
            <p class="card-text">В розыске - Нет
            </p>
            <hr style="position: middle;
  width: 100%;
  height: 2px;
  background-color: #000;
  border: none;
  transform: translateY(-50%);">
            <a  href="{% url 'cars:AfterButton_page' %}" style="text-decoration: none; background-color: grey; color: yellow" onmouseover="this.style.color='yellow'; this.style.backgroundColor='blue';" onmouseout="this.style.color='black'; this.style.backgroundColor='transparent';">Договорится о встрече</a>
    </div>
</div>
<div style="display: flex; flex-wrap: wrap; justify-content: center;">
    <div class="card" style="width: 30rem; margin: 10px; border: 1px solid #000; text-align: center;">
        <img src="https://www.edmunds.com/assets/m/bmw/5-series/2004/oem/2004_bmw_5-series_sedan_525i_fq_oem_1_500.jpg" class="card-img-top" alt="BMW5Series2006" style="width: 480px; height: 250px; background-color: #f0f0f0; display: block; margin: 0 auto;">
        <div class="card-body">
            <hr style="position: middle;
  width: 100%;
  height: 2px;
  background-color: #000;
  border: none;
  transform: translateY(-50%);">
            <h5 class="card-title">BMW 5 Series 2006</h5>
            <hr style="position: middle;
  width: 100%;
  height: 2px;
  background-color: #000;
  border: none;
  transform: translateY(-50%);">
            <p class="card-text">Двигатель - 4.39 л • Бензин
            </p>
            <hr style="position: middle;
  width: 100%;
  height: 2px;
  background-color: #000;
  border: none;
  transform: translateY(-50%);">
            <p class="card-text">Кол-во владельцев - 5
            </p>
            <hr style="position: middle;
  width: 100%;
  height: 2px;
  background-color: #000;
  border: none;
  transform: translateY(-50%);">
            <p class="card-text">В розыске - Нет
            </p>
            <hr style="position: middle;
  width: 100%;
  height: 2px;
  background-color: #000;
  border: none;
  transform: translateY(-50%);">
            <a  href="{% url 'cars:AfterButton_page' %}" style="text-decoration: none; background-color: grey; color: yellow" onmouseover="this.style.color='yellow'; this.style.backgroundColor='blue';" onmouseout="this.style.color='black'; this.style.backgroundColor='transparent';">Договорится о встрече</a>
        </div>
    </div>

    <div class="card" style="width: 30rem; margin: 10px; border: 1px solid #000; text-align: center;">
        <img src="https://s.auto.drom.ru/i24278/c/photos/fullsize/bmw/3-series/bmw_3-series_1118311.jpg" class="card-img-top" alt="BMW3Series2014" style="width: 480px; height: 250px; background-color: #f0f0f0; display: block; margin: 0 auto;">
        <div class="card-body">
            <hr style="position: middle;
  width: 100%;
  height: 2px;
  background-color: #000;
  border: none;
  transform: translateY(-50%);">
            <h5 class="card-title">BMW 3 Series 2014</h5>
            <hr style="position: middle;
  width: 100%;
  height: 2px;
  background-color: #000;
  border: none;
  transform: translateY(-50%);">
            <p class="card-text">Двигатель - 4.39 л • Бензин
            </p>
            <hr style="position: middle;
  width: 100%;
  height: 2px;
  background-color: #000;
  border: none;
  transform: translateY(-50%);">
            <p class="card-text">Кол-во владельцев - 5
            </p>
            <hr style="position: middle;
  width: 100%;
  height: 2px;
  background-color: #000;
  border: none;
  transform: translateY(-50%);">
            <p class="card-text">В розыске - Нет
            </p>
            <hr style="position: middle;
  width: 100%;
  height: 2px;
  background-color: #000;
  border: none;
  transform: translateY(-50%);">
            <a  href="{% url 'cars:AfterButton_page' %}" style="text-decoration: none; background-color: grey; color: yellow" onmouseover="this.style.color='yellow'; this.style.backgroundColor='blue';" onmouseout="this.style.color='black'; this.style.backgroundColor='transparent';">Договорится о встрече</a>
        </div>
    </div>
    </div>
</div>
<div style="display: flex; flex-wrap: wrap; justify-content: center;">
<div style="text-align: center;">
    <h4>©2023</h4>
    <p><a href="https://www.instagram.com/automista/" style="text-decoration: none; color: black;" onmouseover="this.style.color='yellow'; this.style.backgroundColor='blue';" onmouseout="this.style.color='black'; this.style.backgroundColor='transparent';">Instagram</a></p>
    <p><a href="https://www.facebook.com/automista/" style="text-decoration: none; color: black;" onmouseover="this.style.color='yellow'; this.style.backgroundColor='blue';" onmouseout="this.style.color='black'; this.style.backgroundColor='transparent';">Facebook</a></p>
    <p><a href="https://twitter.com/automista" style="text-decoration: none; color: black;" onmouseover="this.style.color='yellow'; this.style.backgroundColor='blue';" onmouseout="this.style.color='black'; this.style.backgroundColor='transparent';">X|Twitter</a></p>
    </div>
<div>
    <p style="margin-left: 150px">Наши контактные данные:</p>
    <p style="margin-left: 200px">+3809991168</p>
    <p style="margin-left: 200px">+3806651645</p>
</div>
</div>
</body>
</html>

automista/cars/templates/Chery.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Chery</title>
</head>
<body>
<header>
    <h1 style="margin-left: 500px;">Это все автомобили марки Chery что мы сейчас можем предложить вам:</h1>
</header>
<div style="display: flex; flex-wrap: wrap; justify-content: center;">
    <div class="card" style="width: 30rem; margin: 10px; border: 1px solid #000; text-align: center;">
        <img src="https://cdn.riastatic.com/photosnewr/auto/new_auto_storage/chery-jetour-x70__2125216-620x465x72.jpg" class="card-img-top" alt="Jetour" style="width: 480px; height: 250px; background-color: #f0f0f0; display: block; margin: 0 auto;">
        <div class="card-body">
            <hr style="position: middle;
  width: 100%;
  height: 2px;
  background-color: #000;
  border: none;
  transform: translateY(-50%);">
            <h5 class="card-title">Chery Jetour X70 2022</h5>
            <hr style="position: middle;
  width: 100%;
  height: 2px;
  background-color: #000;
  border: none;
  transform: translateY(-50%);">
            <p class="card-text">Двигатель - 1.5 л • Бензин
            </p>
            <hr style="position: middle;
  width: 100%;
  height: 2px;
  background-color: #000;
  border: none;
  transform: translateY(-50%);">
            <p class="card-text">Кол-во владельцев - 4
            </p>
            <hr style="position: middle;
  width: 100%;
  height: 2px;
  background-color: #000;
  border: none;
  transform: translateY(-50%);">
            <p class="card-text">В розыске - Нет
            </p>
            <hr style="position: middle;
  width: 100%;
  height: 2px;
  background-color: #000;
  border: none;
  transform: translateY(-50%);">
            <a  href="{% url 'cars:AfterButton_page' %}" style="text-decoration: none; background-color: grey; color: yellow" onmouseover="this.style.color='yellow'; this.style.backgroundColor='blue';" onmouseout="this.style.color='black'; this.style.backgroundColor='transparent';">Договорится о встрече</a>
        </div>
    </div>
     </div>
<div style="display: flex; flex-wrap: wrap; justify-content: center;">
<div style="text-align: center;">
    <h4>©2023</h4>
    <p><a href="https://www.instagram.com/automista/" style="text-decoration: none; color: black;" onmouseover="this.style.color='yellow'; this.style.backgroundColor='blue';" onmouseout="this.style.color='black'; this.style.backgroundColor='transparent';">Instagram</a></p>
    <p><a href="https://www.facebook.com/automista/" style="text-decoration: none; color: black;" onmouseover="this.style.color='yellow'; this.style.backgroundColor='blue';" onmouseout="this.style.color='black'; this.style.backgroundColor='transparent';">Facebook</a></p>
    <p><a href="https://twitter.com/automista" style="text-decoration: none; color: black;" onmouseover="this.style.color='yellow'; this.style.backgroundColor='blue';" onmouseout="this.style.color='black'; this.style.backgroundColor='transparent';">X|Twitter</a></p>
    </div>
<div>
    <p style="margin-left: 150px">Наши контактные данные:</p>
    <p style="margin-left: 200px">+3809991168</p>
    <p style="margin-left: 200px">+3806651645</p>
</div>
</div>
</body>
</html>

automista/cars/templates/Citroen.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Citroen</title>
</head>
<body>
<header>
    <h1 style="margin-left: 500px;">Это все автомобили марки Citroen что мы сейчас можем предложить вам:</h1>
</header>
<div style="display: flex; flex-wrap: wrap; justify-content: center;">
    <div class="card" style="width: 30rem; margin: 10px; border: 1px solid #000; text-align: center;">
        <img src="https://img.autoabc.lv/Citroen-C-Crosser/Citroen-C-Crosser_2007_Apvidus_2214125108.jpg" class="card-img-top" alt="C-Crosser" style="width: 480px; height: 250px; background-color: #f0f0f0; display: block; margin: 0 auto;">
        <div class="card-body">
            <hr style="position: middle;
  width: 100%;
  height: 2px;
  background-color: #000;
  border: none;
  transform: translateY(-50%);">
            <h5 class="card-title">Citroen C-Crosser 2012</h5>
            <hr style="position: middle;
  width: 100%;
  height: 2px;
  background-color: #000;
  border: none;
  transform: translateY(-50%);">
            <p class="card-text">Двигатель - 2.2 л (156.4 к.с. / 115 кВт) • Дизель
            </p>
            <hr style="position: middle;
  width: 100%;
  height: 2px;
  background-color: #000;
  border: none;
  transform: translateY(-50%);">
            <p class="card-text">Кол-во владельцев - 4
            </p>
            <hr style="position: middle;
  width: 100%;
  height: 2px;
  background-color: #000;
  border: none;
  transform: translateY(-50%);">
            <p class="card-text">В розыске - Нет
            </p>
            <hr style="position: middle;
  width: 100%;
  height: 2px;
  background-color: #000;
  border: none;
  transform: translateY(-50%);">
            <a  href="{% url 'cars:AfterButton_page' %}" style="text-decoration: none; background-color: grey; color: yellow" onmouseover="this.style.color='yellow'; this.style.backgroundColor='blue';" onmouseout="this.style.color='black'; this.style.backgroundColor='transparent';">Договорится о встрече</a>
        </div>
    </div>

    <div class="card" style="width: 30rem; margin: 10px; border: 1px solid #000; text-align: center;">
        <img src="https://admin2.automoto.ua/uploads/auto/citroen-c4-6.jpg" class="card-img-top" alt="C4" style="width: 480px; height: 250px; background-color: #f0f0f0; display: block; margin: 0 auto;">
        <div class="card-body">
            <hr style="position: middle;
  width: 100%;
  height: 2px;
  background-color: #000;
  border: none;
  transform: translateY(-50%);">
            <h5 class="card-title">Citroen C4 2022</h5>
            <hr style="position: middle;
  width: 100%;
  height: 2px;
  background-color: #000;
  border: none;
  transform: translateY(-50%);">
            <p class="card-text">Двигатель - 1.5 л • Дизель
            </p>
            <hr style="position: middle;
  width: 100%;
  height: 2px;
  background-color: #000;
  border: none;
  transform: translateY(-50%);">
            <p class="card-text">Кол-во владельцев - 5
            </p>
            <hr style="position: middle;
  width: 100%;
  height: 2px;
  background-color: #000;
  border: none;
  transform: translateY(-50%);">
            <p class="card-text"> Пробег - 200 тыс. км
            </p>
            <hr style="position: middle;
  width: 100%;
  height: 2px;
  background-color: #000;
  border: none;
  transform: translateY(-50%);">
            <a  href="{% url 'cars:AfterButton_page' %}" style="text-decoration: none; background-color: grey; color: yellow" onmouseover="this.style.color='yellow'; this.style.backgroundColor='blue';" onmouseout="this.style.color='black'; this.style.backgroundColor='transparent';">Договорится о встрече</a>
        </div>
    </div>
    </div>
<div style="display: flex; flex-wrap: wrap; justify-content: center;">
<div style="text-align: center;">
    <h4>©2023</h4>
    <p><a href="https://www.instagram.com/automista/" style="text-decoration: none; color: black;" onmouseover="this.style.color='yellow'; this.style.backgroundColor='blue';" onmouseout="this.style.color='black'; this.style.backgroundColor='transparent';">Instagram</a></p>
    <p><a href="https://www.facebook.com/automista/" style="text-decoration: none; color: black;" onmouseover="this.style.color='yellow'; this.style.backgroundColor='blue';" onmouseout="this.style.color='black'; this.style.backgroundColor='transparent';">Facebook</a></p>
    <p><a href="https://twitter.com/automista" style="text-decoration: none; color: black;" onmouseover="this.style.color='yellow'; this.style.backgroundColor='blue';" onmouseout="this.style.color='black'; this.style.backgroundColor='transparent';">X|Twitter</a></p>
    </div>
<div>
    <p style="margin-left: 150px">Наши контактные данные:</p>
    <p style="margin-left: 200px">+3809991168</p>
    <p style="margin-left: 200px">+3806651645</p>
</div>
</div>
</body>
</html>

automista/cars/templates/Jeep.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Jeep</title>
</head>
<body>
<header>
    <h1 style="margin-left: 500px;">Это все автомобили марки Jeep что мы сейчас можем предложить вам:</h1>
</header>
<div style="display: flex; flex-wrap: wrap; justify-content: center;">
    <div class="card" style="width: 30rem; margin: 10px; border: 1px solid #000; text-align: center;">
        <img src="https://img.automoto.ua/auto/Jeep-Compass-chernyiy-Vnedorozhnik-Krossover-2016-c79-38250298.jpg" class="card-img-top" alt="Compass" style="width: 480px; height: 250px; background-color: #f0f0f0; display: block; margin: 0 auto;">
        <div class="card-body">
            <hr style="position: middle;
  width: 100%;
  height: 2px;
  background-color: #000;
  border: none;
  transform: translateY(-50%);">
            <h5 class="card-title">Jeep Compass 2016</h5>
            <hr style="position: middle;
  width: 100%;
  height: 2px;
  background-color: #000;
  border: none;
  transform: translateY(-50%);">
            <p class="card-text">Двигатель - 3 л • Бензин
            </p>
            <hr style="position: middle;
  width: 100%;
  height: 2px;
  background-color: #000;
  border: none;
  transform: translateY(-50%);">
            <p class="card-text">Кол-во владельцев - 4
            </p>
            <hr style="position: middle;
  width: 100%;
  height: 2px;
  background-color: #000;
  border: none;
  transform: translateY(-50%);">
            <p class="card-text">В розыске - Нет
            </p>
            <hr style="position: middle;
  width: 100%;
  height: 2px;
  background-color: #000;
  border: none;
  transform: translateY(-50%);">
            <a  href="{% url 'cars:AfterButton_page' %}" style="text-decoration: none; background-color: grey; color: yellow" onmouseover="this.style.color='yellow'; this.style.backgroundColor='blue';" onmouseout="this.style.color='black'; this.style.backgroundColor='transparent';">Договорится о встрече</a>
        </div>
    </div>
     </div>
<div style="display: flex; flex-wrap: wrap; justify-content: center;">
<div style="text-align: center;">
    <h4>©2023</h4>
    <p><a href="https://www.instagram.com/automista/" style="text-decoration: none; color: black;" onmouseover="this.style.color='yellow'; this.style.backgroundColor='blue';" onmouseout="this.style.color='black'; this.style.backgroundColor='transparent';">Instagram</a></p>
    <p><a href="https://www.facebook.com/automista/" style="text-decoration: none; color: black;" onmouseover="this.style.color='yellow'; this.style.backgroundColor='blue';" onmouseout="this.style.color='black'; this.style.backgroundColor='transparent';">Facebook</a></p>
    <p><a href="https://twitter.com/automista" style="text-decoration: none; color: black;" onmouseover="this.style.color='yellow'; this.style.backgroundColor='blue';" onmouseout="this.style.color='black'; this.style.backgroundColor='transparent';">X|Twitter</a></p>
    </div>
<div>
    <p style="margin-left: 150px">Наши контактные данные:</p>
    <p style="margin-left: 200px">+3809991168</p>
    <p style="margin-left: 200px">+3806651645</p>
</div>
</div>
</body>
</html>

automista/cars/templates/ObrabotkaDannih.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>-_-</title>
</head>
<body>
    <div style="position: absolute; top: 20%; left: 50%; transform: translate(-50%, -50%); border: 1px solid grey; height: 100px">
        <h1>Спасибо что доверяете нам!</h1>
        <p style="margin-left: 20px">В скором времени с вами свяжутся наши сотрудники</p>
    </div>
</body>
</html>

automista/cars/templates/cars/base.html
<!DOCTYPE html>
<html>
<head>
    <title>Automista</title>
</head>
<body>
    <header>
    </header>

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>

    <footer>
    </footer>
</body>
</html>

automista/cars/templates/myapp/footer.html
    </footer>
</body>
</html>

automista/cars/templates/myapp/header.html
<!DOCTYPE html>
<html>
<head>

</head>
<body>
    <header>
        <h1>Мой Заголовок</h1>
        <nav>
            <ul>
                <li><a href="/">Главная</a></li>
                <li><a href="/about/">О нас</a></li>
            </ul>
        </nav>
    </header>

automista/cars/templates/myapp/home.html
{% extends "base.html" %}

{% block content %}
    <h2>Добро пожаловать на главную страницу</h2>
    <p>Текст вашей главной страницы здесь.</p>
{% endblock %}